### ISSUE TITLE
CAS not work?

### ISSUE THREAD

**Issue by UniqLife** [pinterest/pymemcache#226]
from pymemcache.client.base import Client
client = Client(('localhost', 11211))

result, cas = client.gets('key')
client.cas('key', 'value1', cas)

----

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pymemcache/client/base.py", line 437, in cas
    return self._store_cmd(b'cas', {key: value}, expire, noreply, cas)[key]
  File "/my/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pymemcache/client/base.py", line 842, in _store_cmd
    self._raise_errors(line, name)
  File "/my/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pymemcache/client/base.py", line 732, in _raise_errors
    raise MemcacheUnknownCommandError(name)
pymemcache.exceptions.MemcacheUnknownCommandError: b'cas'

**Comment by rtroyanov** [comment]
@UniqLife hello. What was solution of this issue?
