### ISSUE TITLE
Three unit tests failing on isolated VM

### ISSUE THREAD

**Issue by jayvdb** [pinterest/pymemcache#325]
When running the tests in an isolated VM for openSUSE rpm builds, disconnected from the internet, I am encountering the following three test failures.  The openSUSE package is currently at v3.3.0

```py
======================================================================
ERROR: test_socket_close (pymemcache.test.test_client.TestClientSocketConnect)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abuild/rpmbuild/BUILD/pymemcache-3.4.4/pymemcache/test/test_client.py", line 1160, in test_socket_close
    client._connect()
  File "/home/abuild/rpmbuild/BUILD/pymemcache-3.4.4/pymemcache/client/base.py", line 314, in _connect
    s.IPPROTO_TCP)
  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

======================================================================
ERROR: test_socket_close_exception (pymemcache.test.test_client.TestClientSocketConnect)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abuild/rpmbuild/BUILD/pymemcache-3.4.4/pymemcache/test/test_client.py", line 1171, in test_socket_close_exception
    client._connect()
  File "/home/abuild/rpmbuild/BUILD/pymemcache-3.4.4/pymemcache/client/base.py", line 314, in _connect
    s.IPPROTO_TCP)
  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

======================================================================
FAIL: test_socket_connect_closes_on_failure (pymemcache.test.test_client.TestClientSocketConnect)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abuild/rpmbuild/BUILD/pymemcache-3.4.4/pymemcache/test/test_client.py", line 1152, in test_socket_connect_closes_on_failure
    assert len(socket_module.sockets) == 1
AssertionError
```

I am also experiencing errors with the gevent and pylibmc unit tests, and the integration and benchmark tests, but I am still investigating those.

**Comment by jparise** [comment]
Thanks for the report, @jayvdb! This is an oversight that should be corrected by #327.
