### ISSUE TITLE
Unable to flush memcache using flush_all()

### ISSUE THREAD

**Issue by rikeshpatel14** [pinterest/pymemcache#357]
**Sample code**

```
import json
from pymemcache.client.base import Client

client = Client('######:7642')

msg = {"a":"b", "c":"d"}

client.set(key='key', value=json.dumps(msg), expire=0, noreply=False)
result = client.get(key='key', default=None)
print(json.loads(result))

client.flush_all(delay=0, noreply=False)
client.close()
```

Am trying to run the above code to add some dummy key-value data to memcache, and finally flush it, but the _client.flush_all(delay=0, noreply=False)_ is raising an exception _pymemcache.exceptions.MemcacheServerError: b'Command disabled'_ . Please see a sample run below with Python _v3.9.5_. Can you please check why am getting an exception

**Sample run output**
```
########$ python3 test.py 
{'a': 'b', 'c': 'd'}
Traceback (most recent call last):
  File "/Users/rpatel8/Downloads/ca-iot-refrigeration/cache-loader/test.py", line 13, in <module>
    client.flush_all(delay=0, noreply=False)
  File "/usr/local/lib/python3.9/site-packages/pymemcache/client/base.py", line 887, in flush_all
    results = self._misc_cmd([cmd], b'flush_all', noreply)
  File "/usr/local/lib/python3.9/site-packages/pymemcache/client/base.py", line 1137, in _misc_cmd
    self._raise_errors(line, cmd_name)
  File "/usr/local/lib/python3.9/site-packages/pymemcache/client/base.py", line 940, in _raise_errors
    raise MemcacheServerError(error)
pymemcache.exceptions.MemcacheServerError: b'Command disabled'
```

**Comment by cgordon** [comment]
What do you have running on port 7642? Is it memcached or a proxy of some sort? If it is memcached, do you have the "--disable-flush-all" (or "-F") flag passed to it?

**Comment by rikeshpatel14** [comment]
Seems the flush command was disabled. Re-enabling it worked fine. Thank you
