### ISSUE TITLE
BrokenPipeError during set()

### ISSUE THREAD

**Issue by akrherz** [pinterest/pymemcache#377]
Thanks for your efforts on `pymemcache` :)  I have observed a strange error and wished to at least report it for posterity's sake.  I am running memcached with the following options `memcached -p 11211 -u memcached -m 8192 -c 60000 -I 10m` , so in theory, I should be able to write a 10 MB object to memcache.  Instead this happens with an approximate 6 MB file:

```python
>>> from pymemcache.client import Client
>>> mc = Client(["localhost", 11211])
>>> mc.set('test', open('test').read(), 3600)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/prod/lib/python3.10/site-packages/pymemcache/client/base.py", line 462, in set
    return self._store_cmd(b'set', {key: value}, expire, noreply,
  File "/opt/miniconda3/envs/prod/lib/python3.10/site-packages/pymemcache/client/base.py", line 1094, in _store_cmd
    self.sock.sendall(b''.join(cmds))
ConnectionResetError: [Errno 104] Connection reset by peer
>>> mc.set('test', open('test').read()[:5000000], 3600)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/prod/lib/python3.10/site-packages/pymemcache/client/base.py", line 462, in set
    return self._store_cmd(b'set', {key: value}, expire, noreply,
  File "/opt/miniconda3/envs/prod/lib/python3.10/site-packages/pymemcache/client/base.py", line 1094, in _store_cmd
    self.sock.sendall(b''.join(cmds))
BrokenPipeError: [Errno 32] Broken pipe
```

What's interesting though, is that once I restart `memcached`, the writes above work.  So my guess this has something to do with the allocation of object slots and not wanting to evict enough space?  I captured a server status during this time

<details>

```
#localhost:11211        Field         Value
              accepting_conns             1
                    auth_cmds             0
                  auth_errors             0
                        bytes    7560348513
                   bytes_read 1995063460005
                bytes_written 4601288438725
                   cas_badval             0
                     cas_hits             0
                   cas_misses             0
                    cmd_flush             0
                      cmd_get     110857871
                     cmd_meta             3
                      cmd_set      45050895
                    cmd_touch          5549
                  conn_yields        409333
        connection_structures           263
        crawler_items_checked  286468428140
            crawler_reclaimed      22317829
             curr_connections             8
                   curr_items       2950690
                    decr_hits      89073947
                  decr_misses         36662
                  delete_hits          8536
                delete_misses             3
              direct_reclaims       7445874
               evicted_active            73
            evicted_unfetched       2255012
                    evictions       6703482
            expired_unfetched      17136167
                  get_expired       5448172
                  get_flushed             0
                     get_hits      65940797
                   get_misses      44917074
                   hash_bytes      16777216
            hash_is_expanding             0
             hash_power_level            21
                    incr_hits      89001910
                  incr_misses             0
                     libevent  2.1.8-stable
               limit_maxbytes    8589934592
          listen_disabled_num             0
             log_watcher_sent             0
          log_watcher_skipped             0
           log_worker_dropped             0
           log_worker_written             0
            lru_bumps_dropped             0
          lru_crawler_running             0
           lru_crawler_starts      16692910
       lru_maintainer_juggles     622705495
            lrutail_reflocked         41629
                 malloc_fails             0
              max_connections         60000
                moves_to_cold      16135165
                moves_to_warm       5148361
             moves_within_lru       1237136
                          pid          1964
                 pointer_size            64
                    reclaimed       1785517
         rejected_connections             0
                 reserved_fds            20
                rusage_system  45550.184168
                  rusage_user 227739.222670
        slab_global_page_pool             0
   slab_reassign_busy_deletes             0
     slab_reassign_busy_items           563
  slab_reassign_chunk_rescues         10314
slab_reassign_evictions_nomem       3722779
 slab_reassign_inline_reclaim          9502
        slab_reassign_rescues       1541741
        slab_reassign_running             0
                  slabs_moved         96317
                      threads             4
                         time    1645561723
   time_in_listen_disabled_us             0
            total_connections     200734676
                  total_items      46702011
                   touch_hits          5549
                 touch_misses             0
                       uptime      14866433
                      version        1.5.22
```
</details>

So my issue here, is there some server / client interaction that is not being accounted for here when attempting such large-ish writes?  Thank you.

**Comment by martinnj** [comment]
I can't find any references in the changelogs, but with a newer version of the Memcached daemon (`1.6.9`) I no longer get the broken pipes when sending large objects with `noreply=False`.

**Comment by akrherz** [comment]
Thanks for the updates @martinnj !  I'm testing this again with `1.6.15` and am puzzled by what I am currently observing, which is being able to write 500 MB values without error?!?!  Server is running with `memcached -p 11211 -u memcached -m 8192 -c 60000 -I 10m`  Hmmmm

**Comment by martinnj** [comment]
@akrherz likely you have the client constructed with `default_noreply=True` (which is [default](https://github.com/pinterest/pymemcache/blob/master/pymemcache/client/base.py#L283)) or using `client.set("key", "val", noreply=True)`.
If you set either of those to `False` you should get an exception telling you the object is too large.

**Comment by akrherz** [comment]
Yeah, thanks @martinnj , I was wondering about that after I wrote my message.

```python
mc.set('test', open('test').read(), 3600, noreply=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/prod/lib/python3.10/site-packages/pymemcache/client/base.py", line 462, in set
    return self._store_cmd(b'set', {key: value}, expire, noreply,
  File "/opt/miniconda3/envs/prod/lib/python3.10/site-packages/pymemcache/client/base.py", line 1107, in _store_cmd
    self._raise_errors(line, name)
  File "/opt/miniconda3/envs/prod/lib/python3.10/site-packages/pymemcache/client/base.py", line 940, in _raise_errors
    raise MemcacheServerError(error)
pymemcache.exceptions.MemcacheServerError: b'object too large for cache'
```

So it appears my issue is no longer valid with an upgraded memcached server?

**Comment by martinnj** [comment]
Yes, I think we have confirmed that the issue was indeed because of the memcached servers handling of large objects in the ASCII protocol, while the noreply flag was set. :)
