### ISSUE TITLE
Usage on arm servers? Invalid magic error

### ISSUE THREAD

**Issue by musaulker** [pinterest/pymemcache#456]
Hello,

I am trying to use latest version of pymemcache on an Arm64 server.  But I get a weird error about invalid magic.

Here is the sample code to test:

```
from pymemcache.client import base
client = base.Client(('127.0.0.1', 11211))
client.set('test', '123', noreply=False)
```

Python Exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/test/venv/lib/python3.10/site-packages/pymemcache/client/base.py", line 475, in set
    return self._store_cmd(b"set", {key: value}, expire, noreply, flags=flags)[key]
  File "/home/ubuntu/test/venv/lib/python3.10/site-packages/pymemcache/client/base.py", line 1243, in _store_cmd
    buf, line = _readline(self.sock, buf)
  File "/home/ubuntu/test/venv/lib/python3.10/site-packages/pymemcache/client/base.py", line 1660, in _readline
    raise MemcacheUnexpectedCloseError()
pymemcache.exceptions.MemcacheUnexpectedCloseError
```

Memcached server logs:
```
Dec 31 10:18:22 instance-1 systemd-memcached-wrapper[243999]: <23 new binary client connection.
Dec 31 10:18:22 instance-1 systemd-memcached-wrapper[243999]: <23 Read binary protocol data:
Dec 31 10:18:22 instance-1 systemd-memcached-wrapper[243999]: <23    0x73 0x65 0x74 0x20
Dec 31 10:18:22 instance-1 systemd-memcached-wrapper[243999]: <23    0x74 0x65 0x73 0x74
Dec 31 10:18:22 instance-1 systemd-memcached-wrapper[243999]: <23    0x20 0x30 0x20 0x30
Dec 31 10:18:22 instance-1 systemd-memcached-wrapper[243999]: <23    0x20 0x33 0x20 0x6e
Dec 31 10:18:22 instance-1 systemd-memcached-wrapper[243999]: <23    0x6f 0x72 0x65 0x70
Dec 31 10:18:22 instance-1 systemd-memcached-wrapper[243999]: <23    0x6c 0x79 0x0d 0x0a
Dec 31 10:18:22 instance-1 systemd-memcached-wrapper[243999]: Invalid magic:  73
Dec 31 10:18:22 instance-1 systemd-memcached-wrapper[243999]: <23 connection closed.
```

Python version: 3.10.6
Architecture: `Linux instance-1 #31-Ubuntu SMP Fri Nov 25 17:03:15 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux`

How can I solve this problem @jogo @bloodearnest @jd ?

Thank you

**Comment by musaulker** [comment]
Never mind. I just forget a flag (-S) on memcached server while testing the Sasl authentication. So its not related to pymemcache

Thank you for the library.
